# Generated by Django 2.2.6 on 2021-09-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecomment',
            options={'verbose_name': 'likes (комментарии)', 'verbose_name_plural': 'likes (комментарии)'},
        ),
    ]
